import { Philosopher } from "next/font/google";
import "./globals.css";

const roboto = Philosopher({subsets: ['cyrillic'], weight:  '400'});

export const metadata = {
  title: "Корчма",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
